import { fetch } from "frontity";

const fetchMenu = () => {
  let menuJSON = {
    status: "ok",
    menus: [
      {
        id: 2,
        name: "Main Menu",
        description: "",
        slug: "main-menu",
        items: [
          {
            ID: 20074,
            post_author: "1",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2015-07-22 13:09:42",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "open",
            ping_status: "closed",
            post_password: "",
            post_name: "20074",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 0,
            guid: "http://www.capetownetc.com/?p=20074",
            menu_order: 1,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 20074,
            menu_item_parent: "0",
            object_id: "3",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/news/",
            title: "News",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212949,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:12:12",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212949",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 3,
            guid: "https://staging.capetownetc.com/?p=212949",
            menu_order: 2,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212949,
            menu_item_parent: "20074",
            object_id: "10375",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/news/western-cape/",
            title: "Western Cape",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212947,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:12:13",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212947",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 3,
            guid: "https://staging.capetownetc.com/?p=212947",
            menu_order: 3,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212947,
            menu_item_parent: "20074",
            object_id: "10376",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/news/south-africa/",
            title: "South Africa",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212961,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:32:40",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212961",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 3,
            guid: "https://staging.capetownetc.com/?p=212961",
            menu_order: 4,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212961,
            menu_item_parent: "20074",
            object_id: "7747",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/news/world/",
            title: "World",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212946,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:12:18",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212946",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 3,
            guid: "https://staging.capetownetc.com/?p=212946",
            menu_order: 5,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212946,
            menu_item_parent: "20074",
            object_id: "10378",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/news/opinion/",
            title: "Opinion",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212945,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:12:19",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212945",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 3,
            guid: "https://staging.capetownetc.com/?p=212945",
            menu_order: 6,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212945,
            menu_item_parent: "20074",
            object_id: "10379",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/news/good-news/",
            title: "Good News",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212944,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:12:16",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212944",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 3,
            guid: "https://staging.capetownetc.com/?p=212944",
            menu_order: 7,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212944,
            menu_item_parent: "20074",
            object_id: "10380",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/news/business/",
            title: "Business",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212948,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:12:14",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212948",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 3,
            guid: "https://staging.capetownetc.com/?p=212948",
            menu_order: 8,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212948,
            menu_item_parent: "20074",
            object_id: "10381",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/news/sport/",
            title: "Sport",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212963,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 11:53:59",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212963",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 0,
            guid: "https://staging.capetownetc.com/?p=212963",
            menu_order: 9,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212963,
            menu_item_parent: "0",
            object_id: "10366",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/things-to-do/",
            title: "Things To Do",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212952,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:20:40",
            post_content: "",
            post_title: "Food & Drink",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212952",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 10366,
            guid: "https://staging.capetownetc.com/?p=212952",
            menu_order: 10,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212952,
            menu_item_parent: "212963",
            object_id: "13",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/things-to-do/food-and-drink/",
            title: "Food & Drink",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212953,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:20:41",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212953",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 10366,
            guid: "https://staging.capetownetc.com/?p=212953",
            menu_order: 11,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212953,
            menu_item_parent: "212963",
            object_id: "10368",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/things-to-do/adventure/",
            title: "Adventure",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212954,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:20:42",
            post_content: "",
            post_title: "Arts & Culture",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212954",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 10366,
            guid: "https://staging.capetownetc.com/?p=212954",
            menu_order: 12,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212954,
            menu_item_parent: "212963",
            object_id: "7165",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/things-to-do/culture/",
            title: "Arts & Culture",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212955,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:27:55",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212955",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 10366,
            guid: "https://staging.capetownetc.com/?p=212955",
            menu_order: 13,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212955,
            menu_item_parent: "212963",
            object_id: "17",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/things-to-do/family/",
            title: "Family",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212951,
            post_author: "101",
            post_date: "2023-08-30 16:08:04",
            post_date_gmt: "2023-07-26 10:20:43",
            post_content: "",
            post_title: "Travel & Stay",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212951",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:04",
            post_modified_gmt: "2023-08-30 14:08:04",
            post_content_filtered: "",
            post_parent: 10366,
            guid: "https://staging.capetownetc.com/?p=212951",
            menu_order: 14,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212951,
            menu_item_parent: "212963",
            object_id: "495",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/things-to-do/travel/",
            title: "Travel & Stay",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212956,
            post_author: "101",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-07-26 10:27:56",
            post_content: "",
            post_title: "Events & Entertainment",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212956",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 10366,
            guid: "https://staging.capetownetc.com/?p=212956",
            menu_order: 15,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212956,
            menu_item_parent: "212963",
            object_id: "16",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/things-to-do/entertainment/",
            title: "Events & Entertainment",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212957,
            post_author: "101",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-07-26 10:27:57",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212957",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 10366,
            guid: "https://staging.capetownetc.com/?p=212957",
            menu_order: 16,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212957,
            menu_item_parent: "212963",
            object_id: "10373",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/things-to-do/things-to-do-top-guides/",
            title: "Top Guides",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 11,
            post_author: "1",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2014-07-10 11:31:15",
            post_content: "",
            post_title: "Win",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "open",
            ping_status: "closed",
            post_password: "",
            post_name: "11",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 0,
            guid: "http://cape.hsmdns.co.za/?p=11",
            menu_order: 17,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 11,
            menu_item_parent: "0",
            object_id: "10",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/competitions/",
            title: "Win",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212958,
            post_author: "101",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-07-26 10:27:58",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212958",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 0,
            guid: "https://staging.capetownetc.com/?p=212958",
            menu_order: 18,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212958,
            menu_item_parent: "11",
            object_id: "10",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/competitions/",
            title: "Competitions",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212959,
            post_author: "101",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-07-26 10:32:42",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212959",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 0,
            guid: "https://staging.capetownetc.com/?p=212959",
            menu_order: 19,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212959,
            menu_item_parent: "11",
            object_id: "10382",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/photo-of-the-month/",
            title: "Photo Of The Month",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212960,
            post_author: "101",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-07-26 10:32:43",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212960",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 0,
            guid: "https://staging.capetownetc.com/?p=212960",
            menu_order: 20,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212960,
            menu_item_parent: "11",
            object_id: "10383",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/video-of-the-month/",
            title: "Video Of The Month",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212964,
            post_author: "101",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-07-26 12:28:07",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212964",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 0,
            guid: "https://staging.capetownetc.com/?p=212964",
            menu_order: 21,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212964,
            menu_item_parent: "0",
            object_id: "10384",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/vouchers/",
            title: "Vouchers",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 107472,
            post_author: "1",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2019-02-21 08:36:47",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "107472",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 0,
            guid: "https://www.capetownetc.com/?p=107472",
            menu_order: 22,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 107472,
            menu_item_parent: "0",
            object_id: "182",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/videos/",
            title: "Videos",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212910,
            post_author: "1",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-07-25 09:51:24",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212910",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 182,
            guid: "https://staging.capetownetc.com/?p=212910",
            menu_order: 23,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212910,
            menu_item_parent: "107472",
            object_id: "10364",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/videos/news-videos/",
            title: "News",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212911,
            post_author: "1",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-07-25 09:51:24",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212911",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 182,
            guid: "https://staging.capetownetc.com/?p=212911",
            menu_order: 24,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212911,
            menu_item_parent: "107472",
            object_id: "10365",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/videos/things-to-do-video/",
            title: "Things To Do",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212990,
            post_author: "101",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-08-17 07:25:20",
            post_content: "",
            post_title: "Subscribe",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212990",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 0,
            guid: "https://staging.capetownetc.com/?p=212990",
            menu_order: 25,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212990,
            menu_item_parent: "0",
            object_id: "11294",
            object: "page",
            type: "post_type",
            type_label: "Page",
            url: "https://staging.capetownetc.com/subscribe-capetownetc-magazine/",
            title: "Subscribe",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212997,
            post_author: "101",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-08-30 14:04:53",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212997",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 0,
            guid: "https://staging.capetownetc.com/?p=212997",
            menu_order: 26,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212997,
            menu_item_parent: "0",
            object_id: "68166",
            object: "page",
            type: "post_type",
            type_label: "Page",
            url: "https://staging.capetownetc.com/advertising/",
            title: "Advertise",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212986,
            post_author: "101",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-08-07 13:42:01",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "212986",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 0,
            guid: "https://staging.capetownetc.com/?p=212986",
            menu_order: 27,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212986,
            menu_item_parent: "212997",
            object_id: "7263",
            object: "page",
            type: "post_type",
            type_label: "Page",
            url: "https://staging.capetownetc.com/contact/",
            title: "Contact",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 212987,
            post_author: "101",
            post_date: "2023-08-30 16:08:05",
            post_date_gmt: "2023-08-07 13:42:02",
            post_content: "",
            post_title: "Rate Card",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "rate-card",
            to_ping: "",
            pinged: "",
            post_modified: "2023-08-30 16:08:05",
            post_modified_gmt: "2023-08-30 14:08:05",
            post_content_filtered: "",
            post_parent: 0,
            guid: "https://staging.capetownetc.com/?p=212987",
            menu_order: 28,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 212987,
            menu_item_parent: "212997",
            object_id: "68166",
            object: "page",
            type: "post_type",
            type_label: "Page",
            url: "https://staging.capetownetc.com/advertising/",
            title: "Rate Card",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
        ],
        count: 28,
      },
      {
        id: 7536,
        name: "Primary",
        description: "",
        slug: "primary",
        items: [
          {
            ID: 63243,
            post_author: "1",
            post_date: "2017-05-10 21:26:30",
            post_date_gmt: "2017-05-10 19:26:30",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "63243",
            to_ping: "",
            pinged: "",
            post_modified: "2019-12-13 13:51:47",
            post_modified_gmt: "2019-12-13 11:51:47",
            post_content_filtered: "",
            post_parent: 0,
            guid: "http://www.capetownetc.com/?p=63243",
            menu_order: 1,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 63243,
            menu_item_parent: "0",
            object_id: "7165",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/things-to-do/culture/",
            title: "Culture",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 63244,
            post_author: "1",
            post_date: "2017-05-10 21:26:31",
            post_date_gmt: "2017-05-10 19:26:31",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "63244",
            to_ping: "",
            pinged: "",
            post_modified: "2019-12-13 13:51:47",
            post_modified_gmt: "2019-12-13 11:51:47",
            post_content_filtered: "",
            post_parent: 0,
            guid: "http://www.capetownetc.com/?p=63244",
            menu_order: 2,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 63244,
            menu_item_parent: "0",
            object_id: "10",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/competitions/",
            title: "Competitions",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 63241,
            post_author: "1",
            post_date: "2017-05-10 21:26:30",
            post_date_gmt: "2017-05-10 19:26:30",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "63241",
            to_ping: "",
            pinged: "",
            post_modified: "2019-12-13 13:51:47",
            post_modified_gmt: "2019-12-13 11:51:47",
            post_content_filtered: "",
            post_parent: 0,
            guid: "http://www.capetownetc.com/?p=63241",
            menu_order: 3,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 63241,
            menu_item_parent: "0",
            object_id: "3",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/news/",
            title: "News",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
          {
            ID: 63240,
            post_author: "1",
            post_date: "2017-05-10 21:26:30",
            post_date_gmt: "2017-05-10 19:26:30",
            post_content: " ",
            post_title: "",
            post_excerpt: "",
            post_status: "publish",
            comment_status: "closed",
            ping_status: "closed",
            post_password: "",
            post_name: "63240",
            to_ping: "",
            pinged: "",
            post_modified: "2019-12-13 13:51:47",
            post_modified_gmt: "2019-12-13 11:51:47",
            post_content_filtered: "",
            post_parent: 0,
            guid: "http://www.capetownetc.com/?p=63240",
            menu_order: 4,
            post_type: "nav_menu_item",
            post_mime_type: "",
            comment_count: "0",
            filter: "raw",
            db_id: 63240,
            menu_item_parent: "0",
            object_id: "13",
            object: "category",
            type: "taxonomy",
            type_label: "Category",
            url: "https://staging.capetownetc.com/things-to-do/food-and-drink/",
            title: "Food and Drink",
            target: "",
            attr_title: "",
            description: "",
            classes: [""],
            xfn: "",
          },
        ],
        count: 4,
      },
    ],
  };
  //
  //
  //
  //
  //
  //
  const menuData = menuJSON.menus[0].items;
  const data = {};

  for (let i = 0; i < menuData.length; i++) {
    const url = menuData[i].url.substring(
      "https://staging.capetownetc.com".length
    );
    const menu_title = menuData[i].title;
    const menu_item_parent_id = menuData[i].menu_item_parent;
    const id = menuData[i].ID;
    const categoryID = menuData[i].object_id;
    const type = menuData[i].object;

    if (menu_item_parent_id.toString() !== "0" && url !== "/") {
      data[menu_item_parent_id].children.push({
        id: categoryID,
        title: menu_title,
        url: url,
        type: type,
      });
    } else {
      data[id.toString()] = {
        id: categoryID,
        title: menu_title,
        url: url,
        type: type,
        children: [],
      };
    }
  }

  return {
    _20074_: data[20074],
    _212963_: data[212963],
    _11_: data[11],
    _212964_: data[212964],
    _107472_: data[107472],
    _212990_: data[212990],
    _212997_: data[212997],
  };
};
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
// const fetchMenu = async (state) => {
//   const response = await fetch(
//     `${state.source.url}/api/menus/get_menus/?id=secondary` // Replace with your menu slug
//   );
//   let menuJSON = await response.json();
//   const menuData = menuJSON.menus[0].items;
//   const data = {};

//   for (let i = 0; i < menuData.length; i++) {
//     const url = menuData[i].url.substring(state.source.url.length);
//     const menu_title = menuData[i].title;
//     const menu_item_parent_id = menuData[i].menu_item_parent;
//     const id = menuData[i].ID;
//     const categoryID = menuData[i].object_id;
//     const type = menuData[i].object;

//     if (menu_item_parent_id.toString() !== "0" && url !== "/") {
//       data[menu_item_parent_id].children.push({
//         id: categoryID,
//         title: menu_title,
//         url: url,
//         type: type,
//       });
//     } else {
//       data[id.toString()] = {
//         id: categoryID,
//         title: menu_title,
//         url: url,
//         type: type,
//         children: [],
//       };
//     }
//   }

//   return {
//     _20074_: data[20074],
//     _212963_: data[212963],
//     _11_: data[11],
//     _212964_: data[212964],
//     _107472_: data[107472],
//     _212990_: data[212990],
//     _212997_: data[212997],
//   };
// };

export default fetchMenu;
